apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: monitoring
data:
  blackbox.yml: |
    modules:
      http_public:
        prober: http
        timeout: 10s
        http:
          method: GET
          preferred_ip_protocol: ip4
          follow_redirects: true
          valid_status_codes:
            - 200
            - 204
            - 301
            - 302
            - 401
          tls_config:
            insecure_skip_verify: false
      tcp_connect_ipv4:
        prober: tcp
        timeout: 5s
        tcp:
          preferred_ip_protocol: ip4
          ip_protocol_fallback: false
      icmp_ipv4:
        prober: icmp
        timeout: 5s
        icmp:
          preferred_ip_protocol: ip4
          ip_protocol_fallback: false
      dns_liucf_ipv4:
        prober: dns
        timeout: 5s
        dns:
          preferred_ip_protocol: ip4
          ip_protocol_fallback: false
          query_name: liucf.com
          query_type: A
          valid_rcodes:
            - NOERROR
