import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

export interface ApiEnv {
  host: string;
  port: number;
  webOrigin: string;
  /** Release version: APP_VERSION env override, else the root package.json version. */
  appVersion: string;
  /** SQLite state database (sessions, audit events, incidents; node registry stays YAML). */
  databasePath: string;
  nodeConfigPath?: string;
  nodeConfigSeedPath?: string;
  prometheusUrl?: string;
  prometheusTimeoutMs: number;
  prometheusBasicAuthUsername?: string;
  prometheusBasicAuthPassword?: string;
  prometheusBearerToken?: string;
  statusCacheTtlSeconds: number;
  alertmanagerUrl?: string;
  alertmanagerTimeoutMs: number;
  alertmanagerWebhookToken?: string;
  /** Prometheus job label of the blackbox HTTP probes ("" disables /api/latency). */
  probeJob: string;
  /** Optional non-secret RIPE Atlas measurement mapping generated by the setup script. */
  ripeAtlasConfigPath?: string;
  ripeAtlasTimeoutMs: number;
  // Auth (owner from env; revocable SQLite-backed signed-cookie sessions).
  cookieSecret: string;
  secureCookie: boolean;
  sessionTtlSeconds: number;
  incidentRetentionDays: number;
  auditRetentionDays: number;
  revokedSessionRetentionDays: number;
  /** Timestamp file written only after a successful off-site backup copy. */
  backupSuccessTimestampPath: string;
  backupRequestPath: string;
  backupLastResultPath: string;
  settingsEncryptionKey?: string;
  lokiUrl?: string;
  notificationAllowedHosts: string[];
  allowRegister: boolean;
  initialOwnerEmail?: string;
  initialOwnerPassword?: string;
  // GitHub OAuth login. Only the account whose login === githubOwnerLogin is
  // accepted as owner; everyone else is rejected.
  githubClientId?: string;
  githubClientSecret?: string;
  githubOwnerLogin?: string;
  githubCallbackUrl?: string;
  publicBaseUrl?: string;
}

function numberFromEnv(name: string, fallback: number): number {
  const raw = process.env[name];
  if (!raw) return fallback;
  const parsed = Number.parseInt(raw, 10);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function boolFromEnv(name: string, fallback: boolean): boolean {
  const raw = process.env[name]?.trim().toLowerCase();
  if (!raw) return fallback;
  return raw === "true" || raw === "1" || raw === "yes";
}

/**
 * Single-sourced release version: the root package.json is the only place a
 * release bump is written (deploy.sh and the image tag both read it). The
 * APP_VERSION env stays as an override for ad-hoc builds.
 */
function readAppVersion(): string {
  const override = process.env.APP_VERSION?.trim();
  if (override) return override;
  try {
    const rootPackageJson = fileURLToPath(new URL("../../../../package.json", import.meta.url));
    const parsed = JSON.parse(readFileSync(rootPackageJson, "utf8")) as { version?: string };
    return parsed.version?.trim() || "dev";
  } catch {
    return "dev";
  }
}

export function loadEnv(): ApiEnv {
  const nodeEnv = process.env.NODE_ENV ?? "development";
  const prometheusUrl = process.env.PROMETHEUS_URL?.trim();
  const prometheusBasicAuthUsername = process.env.PROMETHEUS_BASIC_AUTH_USERNAME?.trim();
  const prometheusBasicAuthPassword = process.env.PROMETHEUS_BASIC_AUTH_PASSWORD?.trim();
  const prometheusBearerToken = process.env.PROMETHEUS_BEARER_TOKEN?.trim();
  const alertmanagerUrl = process.env.ALERTMANAGER_URL?.trim();
  const alertmanagerWebhookToken = process.env.ALERTMANAGER_WEBHOOK_TOKEN?.trim();
  const cookieSecret = process.env.COOKIE_SECRET?.trim();
  const initialOwnerEmail = process.env.INITIAL_OWNER_EMAIL?.trim();
  const initialOwnerPassword = process.env.INITIAL_OWNER_PASSWORD;
  const githubClientId = process.env.GITHUB_CLIENT_ID?.trim();
  const githubClientSecret = process.env.GITHUB_CLIENT_SECRET?.trim();
  const githubOwnerLogin = process.env.GITHUB_OWNER_LOGIN?.trim();
  const githubCallbackUrl = process.env.GITHUB_CALLBACK_URL?.trim();
  const publicBaseUrl = process.env.PUBLIC_BASE_URL?.trim();
  const ripeAtlasConfigPath = process.env.RIPE_ATLAS_CONFIG_PATH?.trim();
  const lokiUrl = process.env.LOKI_URL?.trim();
  const settingsEncryptionKey = process.env.SETTINGS_ENCRYPTION_KEY?.trim();
  const notificationAllowedHosts = (process.env.NOTIFICATION_ALLOWED_HOSTS ?? "").split(",").map((host) => host.trim().toLowerCase()).filter(Boolean);

  return {
    host: process.env.API_HOST ?? "0.0.0.0",
    port: numberFromEnv("API_PORT", 3001),
    webOrigin: process.env.WEB_ORIGIN ?? "http://localhost:5173",
    appVersion: readAppVersion(),
    databasePath:
      process.env.NODEBEACON_DATABASE_PATH?.trim() ||
      (nodeEnv === "production" ? "/data/nodebeacon.db" : nodeEnv === "test" ? ":memory:" : "./data/nodebeacon.db"),
    nodeConfigPath: process.env.NODEBEACON_NODE_CONFIG,
    nodeConfigSeedPath: process.env.NODEBEACON_NODE_CONFIG_SEED,
    prometheusUrl: prometheusUrl || undefined,
    prometheusTimeoutMs: numberFromEnv("PROMETHEUS_TIMEOUT_MS", 5000),
    prometheusBasicAuthUsername: prometheusBasicAuthUsername || undefined,
    prometheusBasicAuthPassword: prometheusBasicAuthPassword || undefined,
    prometheusBearerToken: prometheusBearerToken || undefined,
    statusCacheTtlSeconds: numberFromEnv("STATUS_CACHE_TTL_SECONDS", 30),
    alertmanagerUrl: alertmanagerUrl || undefined,
    alertmanagerTimeoutMs: numberFromEnv("ALERTMANAGER_TIMEOUT_MS", 5000),
    alertmanagerWebhookToken: alertmanagerWebhookToken || undefined,
    probeJob: process.env.PROBE_JOB?.trim() ?? "blackbox-http-public",
    ripeAtlasConfigPath: ripeAtlasConfigPath || undefined,
    ripeAtlasTimeoutMs: numberFromEnv("RIPE_ATLAS_TIMEOUT_MS", 10_000),
    // A dev-only fallback keeps local `pnpm dev` working without a .env; in
    // production COOKIE_SECRET must be set (see the k8s Secret).
    cookieSecret: cookieSecret || "nodebeacon-dev-insecure-cookie-secret-change-me",
    secureCookie: nodeEnv === "production",
    sessionTtlSeconds: numberFromEnv("SESSION_TTL_SECONDS", 7 * 24 * 60 * 60),
    incidentRetentionDays: numberFromEnv("INCIDENT_RETENTION_DAYS", 180),
    auditRetentionDays: numberFromEnv("AUDIT_RETENTION_DAYS", 365),
    revokedSessionRetentionDays: numberFromEnv("REVOKED_SESSION_RETENTION_DAYS", 30),
    backupSuccessTimestampPath:
      process.env.NODEBEACON_BACKUP_SUCCESS_PATH?.trim() ||
      (nodeEnv === "production" ? "/data/backup-last-success.timestamp" : "./data/backup-last-success.timestamp"),
    backupRequestPath:
      process.env.NODEBEACON_BACKUP_REQUEST_PATH?.trim() ||
      (nodeEnv === "production" ? "/data/backup-request.json" : "./data/backup-request.json"),
    backupLastResultPath:
      process.env.NODEBEACON_BACKUP_LAST_RESULT_PATH?.trim() ||
      (nodeEnv === "production" ? "/data/backup-last-result.json" : "./data/backup-last-result.json"),
    settingsEncryptionKey: settingsEncryptionKey || undefined,
    lokiUrl: lokiUrl || undefined,
    notificationAllowedHosts,
    allowRegister: boolFromEnv("ALLOW_REGISTER", false),
    initialOwnerEmail: initialOwnerEmail || undefined,
    initialOwnerPassword: initialOwnerPassword || undefined,
    githubClientId: githubClientId || undefined,
    githubClientSecret: githubClientSecret || undefined,
    githubOwnerLogin: githubOwnerLogin || undefined,
    githubCallbackUrl: githubCallbackUrl || undefined,
    publicBaseUrl: publicBaseUrl || undefined
  };
}
