import type { FastifyInstance } from "fastify";
import { buildApiError } from "@nodebeacon/shared";
import type { ApiEnv } from "../config/env.js";
import type { AuditService } from "../services/auditService.js";
import type { SqliteDatabase } from "../services/database.js";
import { createNotificationService, type NotificationChannelType } from "../services/notificationService.js";

function record(value: unknown): Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : {}; }

export async function registerAdminNotificationRoutes(app: FastifyInstance, env: ApiEnv, db: SqliteDatabase, audit: AuditService): Promise<void> {
  const service = createNotificationService(db, env); const owner = { preHandler: app.requireOwner };
  app.get("/api/admin/notification-channels", owner, async () => ({ channels: service.listChannels() }));
  app.post("/api/admin/notification-channels", owner, async (request, reply) => { try { const body = record(request.body); return service.saveChannel({ name: String(body.name ?? ""), type: String(body.type ?? "") as NotificationChannelType, config: record(body.config), enabled: body.enabled !== false }); } catch (error) { return reply.code(400).send(buildApiError("invalid_channel", error instanceof Error ? error.message : "Invalid channel.")); } });
  app.patch<{ Params: { id: string } }>("/api/admin/notification-channels/:id", owner, async (request, reply) => { try { const body = record(request.body); const existing = service.listChannels().find((item) => item.id === request.params.id); if (!existing) return reply.code(404).send(buildApiError("not_found", "Channel not found.")); return service.saveChannel({ id: existing.id, name: typeof body.name === "string" ? body.name : existing.name, type: (body.type ?? existing.type) as NotificationChannelType, config: record(body.config), enabled: body.enabled !== false }); } catch (error) { return reply.code(400).send(buildApiError("invalid_channel", error instanceof Error ? error.message : "Invalid channel.")); } });
  app.delete<{ Params: { id: string } }>("/api/admin/notification-channels/:id", owner, async (request) => ({ status: service.deleteChannel(request.params.id) ? "ok" : "not_found" }));
  app.post<{ Params: { id: string } }>("/api/admin/notification-channels/:id/test", owner, async (request, reply) => { const channel = service.listChannels().find((item) => item.id === request.params.id); if (!channel) return reply.code(404).send(buildApiError("not_found", "Channel not found.")); audit.record({ actor: request.user?.id ?? "owner", action: "notification.test", entityId: channel.id }); return { status: "queued", channel: channel.id }; });
  app.get("/api/admin/alert-rules", owner, async () => ({ rules: service.listRules() }));
  app.get("/api/admin/notification-outbox", owner, async () => ({ deliveries: db.prepare("SELECT id,channel_id AS channelId,event_type AS eventType,status,attempts,last_error AS lastError,sent_at AS sentAt,created_at AS createdAt FROM notification_outbox ORDER BY created_at DESC LIMIT 200").all() }));
  app.post("/api/admin/alert-rules", owner, async (request, reply) => { const body = record(request.body); const type = String(body.type); if (type !== "offline" && type !== "load") return reply.code(400).send(buildApiError("invalid_rule", "Only offline and load rules are supported.")); return service.saveRule({ name: String(body.name ?? "Rule"), type, nodeId: typeof body.nodeId === "string" ? body.nodeId : undefined, config: record(body.config), channelIds: Array.isArray(body.channelIds) ? body.channelIds.map(String) : [], enabled: body.enabled !== false }); });
  app.patch<{ Params: { id: string } }>("/api/admin/alert-rules/:id", owner, async (request, reply) => { const current = service.listRules().find((rule) => rule.id === request.params.id); if (!current) return reply.code(404).send(buildApiError("not_found", "Rule not found.")); const body = record(request.body); return service.saveRule({ id: current.id, name: typeof body.name === "string" ? body.name : current.name, type: current.type, nodeId: typeof body.nodeId === "string" ? body.nodeId : current.nodeId, config: record(body.config ?? current.config), channelIds: Array.isArray(body.channelIds) ? body.channelIds.map(String) : current.channelIds, enabled: body.enabled === undefined ? current.enabled : body.enabled === true }); });
  app.delete<{ Params: { id: string } }>("/api/admin/alert-rules/:id", owner, async (request) => ({ status: service.deleteRule(request.params.id) ? "ok" : "not_found" }));
  app.get("/api/admin/traffic-reports", owner, async () => ({ reports: db.prepare("SELECT id,name,period,time,timezone,node_ids_json AS nodeIds,channel_ids_json AS channelIds,enabled FROM traffic_reports ORDER BY created_at DESC").all() }));
  app.post("/api/admin/traffic-reports", owner, async (request) => { const body = record(request.body); const id = `traffic-${Date.now()}`; db.prepare("INSERT INTO traffic_reports(id,name,period,time,timezone,node_ids_json,channel_ids_json,enabled,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)").run(id, String(body.name ?? "Traffic report"), String(body.period ?? "daily"), String(body.time ?? "09:00"), String(body.timezone ?? "Asia/Shanghai"), JSON.stringify(Array.isArray(body.nodeIds) ? body.nodeIds : []), JSON.stringify(Array.isArray(body.channelIds) ? body.channelIds : []), body.enabled === false ? 0 : 1, Date.now(), Date.now()); return { id }; });
  app.post("/api/internal/reports/tick", async (request, reply) => { if (env.alertmanagerWebhookToken && request.headers.authorization !== `Bearer ${env.alertmanagerWebhookToken}`) return reply.code(401).send(buildApiError("unauthorized", "Internal token required.")); return { status: "ok", dispatched: await service.dispatchPending(request.log) }; });
}
