apiVersion: v1
kind: Pod
metadata:
  name: nodebeacon-restore
  namespace: nodebeacon
spec:
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  containers:
    - name: restore
      image: nodebeacon:1.0.39
      imagePullPolicy: Never
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: nodebeacon-data
